import Foundation

struct ReportInput {
    let medName: String
    let windowDays: Int
    let doseDays: [Date]
    let doses: [(Date, Double)]
    let weights: [(Date, Double)]
    let sideEffects: [(Date, String, Int)]
    let metric: Bool
    let today: Date
}

enum ReportComposer {
    static func compose(_ input: ReportInput, calendar: Calendar) -> String {
        let end = calendar.startOfDay(for: input.today)
        let start = calendar.date(byAdding: .day, value: -(input.windowDays - 1), to: end)!

        var lines: [String] = []
        lines.append("GLPill — Doctor Visit Summary")
        lines.append("Medication: \(input.medName)")
        lines.append("Window: last \(input.windowDays) days (ending \(dateString(end)))")
        lines.append("")
        lines.append(adherenceLine(input, start: start, end: end, calendar: calendar))
        lines.append(dosesLine(input, start: start, end: end, calendar: calendar))
        lines.append(weightLine(input, start: start, end: end, calendar: calendar))
        lines.append("")
        lines.append("Side effects:")
        lines.append(contentsOf: sideEffectLines(input, start: start, end: end, calendar: calendar))
        lines.append("")
        lines.append("Generated by GLPill. This summary is for discussion with your clinician and is not medical advice.")
        return lines.joined(separator: "\n")
    }

    private static func adherenceLine(_ input: ReportInput, start: Date, end: Date, calendar: Calendar) -> String {
        let percent = StreakCalculator.adherencePercent(doseDays: input.doseDays, from: start, to: end, calendar: calendar)
        let dosedDays = Set(input.doseDays.map { calendar.startOfDay(for: $0) })
            .filter { $0 >= start && $0 <= end }
            .count
        return "Adherence: \(percent)% (\(dosedDays) of \(input.windowDays) days)"
    }

    private static func dosesLine(_ input: ReportInput, start: Date, end: Date, calendar: Calendar) -> String {
        let doseValues = input.doses
            .filter { calendar.startOfDay(for: $0.0) >= start && calendar.startOfDay(for: $0.0) <= end }
            .map(\.1)
        let unique = Array(Set(doseValues)).sorted()
        guard !unique.isEmpty else { return "Doses taken: none logged" }
        let formatted = unique.map { String(format: "%g mg", $0) }.joined(separator: " → ")
        return "Doses taken: \(formatted)"
    }

    private static func weightLine(_ input: ReportInput, start: Date, end: Date, calendar: Calendar) -> String {
        let inWindow = input.weights
            .filter { calendar.startOfDay(for: $0.0) >= start && calendar.startOfDay(for: $0.0) <= end }
            .map { (date: $0.0, kg: $0.1) }
        guard let change = WeightStats.totalChange(entries: inWindow) else {
            return "Weight change: not enough data"
        }
        let sorted = inWindow.sorted { $0.date < $1.date }
        let first = UnitFormat.weightString(kilograms: sorted.first!.kg, metric: input.metric)
        let last = UnitFormat.weightString(kilograms: sorted.last!.kg, metric: input.metric)
        let delta = input.metric ? change : change / UnitFormat.kgPerLb
        let unit = input.metric ? "kg" : "lb"
        return String(format: "Weight change: %+.1f %@ (%@ → %@)", delta, unit, first, last)
    }

    private static func sideEffectLines(_ input: ReportInput, start: Date, end: Date, calendar: Calendar) -> [String] {
        let inWindow = input.sideEffects.filter {
            let d = calendar.startOfDay(for: $0.0)
            return d >= start && d <= end
        }
        guard !inWindow.isEmpty else { return ["- None logged"] }

        var counts: [String: (count: Int, maxSeverity: Int)] = [:]
        for (_, name, severity) in inWindow {
            let existing = counts[name] ?? (0, 0)
            counts[name] = (existing.count + 1, max(existing.maxSeverity, severity))
        }
        return counts
            .sorted { $0.value.count == $1.value.count ? $0.key < $1.key : $0.value.count > $1.value.count }
            .map { "- \($0.key): \($0.value.count)x (max severity \($0.value.maxSeverity)/3)" }
    }

    private static func dateString(_ date: Date) -> String {
        date.formatted(date: .abbreviated, time: .omitted)
    }
}
