import Foundation

struct ReportInput {
    let medName: String
    let windowDays: Int
    let doseDays: [Date]
    let doses: [(Date, Double)]
    let weights: [(Date, Double)]
    let sideEffects: [(Date, String, Int)]
    let metric: Bool
    let today: Date
    /// Earliest day the user could have dosed (min of settings.startDate and
    /// first dose). The adherence denominator and gap scan are floored to this
    /// so a 3-day-old user reads "3 of 3 days", not "10% of 30".
    let planStart: Date?
}

enum ReportComposer {
    static func compose(_ input: ReportInput, calendar: Calendar) -> String {
        let end = calendar.startOfDay(for: input.today)
        let windowStart = calendar.date(byAdding: .day, value: -(input.windowDays - 1), to: end)!
        // Floor the window to the day the user actually started, so a brand-new
        // user isn't scored against days before their plan existed.
        let start: Date = {
            guard let planStart = input.planStart else { return windowStart }
            return max(windowStart, calendar.startOfDay(for: planStart))
        }()
        let effectiveDays = (calendar.dateComponents([.day], from: start, to: end).day ?? 0) + 1

        var lines: [String] = []
        lines.append("GLPill — Doctor Visit Summary")
        lines.append("Medication: \(input.medName)")
        lines.append("Window: last \(effectiveDays) days (ending \(dateString(end)))")
        lines.append("")
        lines.append(adherenceLine(input, start: start, end: end, windowDays: effectiveDays, calendar: calendar))
        lines.append(gapLine(input, start: start, end: end, calendar: calendar))
        lines.append(dosesLine(input, start: start, end: end, calendar: calendar))
        lines.append(weightLine(input, start: start, end: end, calendar: calendar))
        lines.append("")
        lines.append("Side effects:")
        lines.append(contentsOf: sideEffectLines(input, start: start, end: end, calendar: calendar))
        lines.append("")
        lines.append("Generated by GLPill. This summary is for discussion with your clinician and is not medical advice.")
        return lines.joined(separator: "\n")
    }

    private static func adherenceLine(_ input: ReportInput, start: Date, end: Date, windowDays: Int, calendar: Calendar) -> String {
        let percent = StreakCalculator.adherencePercent(doseDays: input.doseDays, from: start, to: end, calendar: calendar)
        let dosedDays = Set(input.doseDays.map { calendar.startOfDay(for: $0) })
            .filter { $0 >= start && $0 <= end }
            .count
        return "Adherence: \(percent)% (\(dosedDays) of \(windowDays) days)"
    }

    private static func gapLine(_ input: ReportInput, start: Date, end: Date, calendar: Calendar) -> String {
        let gap = AdherenceStats.longestGapDays(doseDays: input.doseDays, from: start, to: end, calendar: calendar, today: input.today)
        return gap > 0 ? "Longest gap: \(gap) days" : "Longest gap: none"
    }

    private static func dosesLine(_ input: ReportInput, start: Date, end: Date, calendar: Calendar) -> String {
        let doseValues = input.doses
            .filter { calendar.startOfDay(for: $0.0) >= start && calendar.startOfDay(for: $0.0) <= end }
            .map(\.1)
            .filter { $0 > 0 } // drop "unknown" (0 mg) doses so an unset plan isn't reported as "0 mg"
        let unique = Array(Set(doseValues)).sorted()
        guard !unique.isEmpty else { return "Doses recorded: not recorded" }
        // Non-directional: a de-escalation (14→7) must not read as an escalation.
        let formatted = unique.map { String(format: "%g mg", $0) }.joined(separator: ", ")
        return "Doses recorded: \(formatted)"
    }

    private static func weightLine(_ input: ReportInput, start: Date, end: Date, calendar: Calendar) -> String {
        let inWindow = input.weights
            .filter { calendar.startOfDay(for: $0.0) >= start && calendar.startOfDay(for: $0.0) <= end }
            .map { (date: $0.0, kg: $0.1) }
        guard let change = WeightStats.totalChange(entries: inWindow) else {
            return "Weight change: not enough data"
        }
        let sorted = inWindow.sorted { $0.date < $1.date }
        let first = UnitFormat.weightString(kilograms: sorted.first!.kg, metric: input.metric)
        let last = UnitFormat.weightString(kilograms: sorted.last!.kg, metric: input.metric)
        let delta = input.metric ? change : change / UnitFormat.kgPerLb
        let unit = input.metric ? "kg" : "lb"
        return String(format: "Weight change: %+.1f %@ (%@ → %@)", delta, unit, first, last)
    }

    private static func sideEffectLines(_ input: ReportInput, start: Date, end: Date, calendar: Calendar) -> [String] {
        let inWindow = input.sideEffects.filter {
            let d = calendar.startOfDay(for: $0.0)
            return d >= start && d <= end
        }
        guard !inWindow.isEmpty else { return ["- None logged"] }

        var counts: [String: (count: Int, maxSeverity: Int)] = [:]
        for (_, name, severity) in inWindow {
            let existing = counts[name] ?? (0, 0)
            counts[name] = (existing.count + 1, max(existing.maxSeverity, severity))
        }
        return counts
            .sorted { $0.value.count == $1.value.count ? $0.key < $1.key : $0.value.count > $1.value.count }
            .map { "- \($0.key): \($0.value.count)x (max severity \($0.value.maxSeverity)/3)" }
    }

    /// Fixed en_US_POSIX so the whole clinician report stays consistent ASCII
    /// (no localized/Devanagari numerals mixed with ASCII numbers elsewhere).
    private static let dateFormatter: DateFormatter = {
        let formatter = DateFormatter()
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.dateFormat = "MMM d, yyyy"
        return formatter
    }()

    private static func dateString(_ date: Date) -> String {
        dateFormatter.string(from: date)
    }
}
